name: freelens
version: 1.2.1 # datasource=github-releases depName=freelensapp/freelens
title: Freelens
summary: Free IDE for Kubernetes
description: |
  Freelens is a Kubernetes IDE that provides a graphical interface for
  managing and monitoring Kubernetes clusters.

  It simplifies cluster operations by offering:

  - A dashboard with real-time cluster insights
  - Support for multiple clusters
  - Built-in terminal access to nodes and pods
  - Visualization of workloads, networking, storage, and configurations
  - Extension support to add custom functionality

  Freelens is maintained by the community.

icon: icon.png

base: core22

grade: stable
confinement: classic

architectures:
  - build-on:
      - amd64
  - build-on:
      - arm64

parts:
  freelens:
    plugin: dump
    source: https://github.com/freelensapp/freelens/releases/download/v$SNAPCRAFT_PROJECT_VERSION/Freelens-$SNAPCRAFT_PROJECT_VERSION-linux-$CRAFT_ARCH_BUILD_FOR.deb
    source-type: deb
    parse-info:
      - usr/share/metainfo/app.freelens.Freelens.metainfo.xml
    stage-packages:
      - ca-certificates
      - gsettings-desktop-schemas
      - libasound2
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo2
      - libcanberra-gtk3-module
      - libcurl3-gnutls
      - libcurl3-nss
      - libcurl4
      - libdrm2
      - libegl1
      - libgbm1
      - libgdk-pixbuf2.0-0
      - libgl1
      - libgles2
      - libglib2.0-0
      - libglib2.0-bin
      - libgtk-3-0
      - libibus-1.0-5
      - libnotify4
      - libnss3
      - libpango-1.0-0
      - libsecret-1-0
      - libtiff5
      - libuuid1
      - libwayland-egl1
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxkbcommon0
      - libxkbfile1
      - libxrandr2
      - libxss1
      - libxtst6
      - locales-all
      - packagekit-gtk3-module
      - patchelf
      - xdg-utils
      - xkb-data
    prime:
      - -opt/Freelens/chrome-sandbox
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/lintian
      - -usr/share/man
    override-build: |
      craftctl default
      patchelf --force-rpath --set-rpath '$ORIGIN/../../lib/x86_64-linux-gnu:$ORIGIN:/snap/core22/current/lib/x86_64-linux-gnu' $CRAFT_PART_INSTALL/opt/Freelens/chrome_crashpad_handler
  gui:
    after:
      - freelens
    plugin: dump
    source: gui
  cleanup:
    after:
      - freelens
      - gui
    plugin: nil
    build-snaps:
      - core22
    override-prime: |
      patchelf --print-rpath $CRAFT_PRIME/opt/Freelens/chrome_crashpad_handler

apps:
  freelens:
    common-id: app.freelens.Freelens
    command: freelens-launch
    desktop: freelens.desktop
