name: freelens
version: 0.1.0
title: Freelens
summary: Freelens
description: Freelens - FOSS IDE for Kubernetes
icon: icon.png

base: core20

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64

parts:
  freelens:
    plugin: dump
    source:
      - to amd64: https://github.com/freelensapp/freelens-nightly-builds/releases/download/nightly-2025-01-08/Freelens-0.1.0-nightly-2025-01-08-linux-amd64.deb
      - to arm64: https://github.com/freelensapp/freelens-nightly-builds/releases/download/nightly-2025-01-08/Freelens-0.1.0-nightly-2025-01-08-linux-arm64.deb
    source-type: deb
    stage-packages:
      - ca-certificates
      - libasound2
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo2
      - libcanberra-gtk3-module
      - libcurl3-gnutls
      - libcurl3-nss
      - libcurl4
      - libegl1
      - libdrm2
      - libgbm1
      - libgl1
      - libgles2
      - libglib2.0-0
      - libgtk-3-0
      - libibus-1.0-5
      - libnss3
      - libpango-1.0-0
      - libsecret-1-0
      - libtiff5
      - libwayland-egl1
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxkbcommon0
      - libxkbfile1
      - libxrandr2
      - libxss1
      - locales-all
      - packagekit-gtk3-module
      - patchelf
      - xdg-utils
      - xkb-data
    prime:
      - -opt/Freelens/chrome-sandbox
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/lintian
      - -usr/share/man
    override-build: |
      snapcraftctl build
      patchelf --force-rpath --set-rpath '$ORIGIN/../../lib/x86_64-linux-gnu:$ORIGIN:/snap/core20/current/lib/x86_64-linux-gnu' $SNAPCRAFT_PART_INSTALL/opt/Freelens/chrome_crashpad_handler
  gui:
    after:
      - freelens
    plugin: dump
    source: gui
  cleanup:
    after:
      - freelens
      - gui
    plugin: nil
    build-snaps:
      - core20
    override-prime: |
      set -eux
      for snap in core20; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      patchelf --print-rpath $SNAPCRAFT_PRIME/opt/Freelens/chrome_crashpad_handler

plugs:
  dot-freelens:
    interface: personal-files
    write:
      - $HOME/.freelens
  dot-kube:
    interface: personal-files
    write:
      - $HOME/.kube
  etc-vulkan:
    interface: system-files
    read:
      - /etc/glvnd/egl_vendor.d
      - /etc/vulkan
  gnome-3-38-2004:
    default-provider: gnome-3-38-2004
    interface: content
    target: $SNAP/gnome-platform
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/icons
  sound-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/sounds

apps:
  freelens:
    common-id: app.freelens.Freelens
    command: freelens-launch
    desktop: usr/share/applications/freelens.desktop
    plugs:
      - browser-support
      - dot-freelens
      - dot-kube
      - etc-vulkan
      - network
      - network-manager
      - network-manager-observe
      - process-control
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
