#!/usr/bin/env bash

SNAP=${SNAP//\/var\/lib\/snapd/}

export NOTIFY_IGNORE_PORTAL=1

REALHOME=$(getent passwd "$UID" | cut -d ':' -f 6 || true)
export REALHOME

if [[ ! -e $HOME/.freelens ]]; then
  ln -s "$REALHOME/.freelens" "$HOME/"
fi

if [[ ! -e $HOME/.kube ]]; then
  ln -s "$REALHOME/.kube" "$HOME/"
fi

export TMPDIR=${XDG_RUNTIME_DIR:-$HOME/.freelens/tmp}

if [[ ! -e $TMPDIR ]]; then
  mkdir -p "$TMPDIR"
  chmod 700 "$TMPDIR"
fi

function prepend_dir() {
  local -n var="$1"
  local dir="$2"
  if [[ $dir == *"\$"* || -d $dir ]]; then
    export "${!var}=${dir}${var:+:$var}"
  fi
}

prepend_dir XDG_CONFIG_DIRS "$SNAP/etc/xdg"

prepend_dir XDG_DATA_DIRS "$SNAP/usr/share"
prepend_dir XDG_DATA_DIRS "$SNAP/share"
prepend_dir XDG_DATA_DIRS "$SNAP/data-dir"
prepend_dir XDG_DATA_DIRS "$SNAP_USER_DATA"

export XDG_DATA_HOME="$SNAP_USER_DATA/.local/share"
mkdir -p "$XDG_DATA_HOME"

prepend_dir XDG_DATA_DIRS "$XDG_DATA_HOME"

exec "$SNAP/opt/Freelens/freelens" --no-sandbox --ozone-platform-hint=auto --disable-seccomp-filter-sandbox "$@"
